swagger: '2.0'
info:
  description: This is the Service Info Swagger Rest Documentation
  version: version
  title: Service Info REST API
host: cross-dev.int.ocp.porscheinformatik.cloud
basePath: /retail/module/api/version
tags:
  - name: ServiceInfo
schemes:
  - https
paths:
  /service-info:
    get:
      tags:
        - ServiceInfo
      summary: Get servie info of a module
      operationId: getServiceInfo
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ServiceInfoType'
securityDefinitions:
  Country:
    type: apiKey
    name: Country
    in: header
  Dealer-Number:
    type: apiKey
    name: Dealer-Number
    in: header
  Brand:
    type: apiKey
    name: Brand
    in: header
security:
  - Country: []
  - Dealer-Number: []
  - Brand: []
definitions:
  ServiceInfoType:
    type: object
    description: Service info object
    properties:
      name:
        type: string
        description: Name of service
      status:
        type: string
        description: Status of service
      system:
        type: string
        description: Providing system
      versions:
        type: array
        items:
          $ref: '#/definitions/VersionType'
  VersionType:
    type: object
    description: Version of Service
    properties:
      version:
        type: number
        description: Version number
      format:
        type: string
        description: Provided data fromat (JSON, XML, ...)
